version: 0.2

env:
  variables:
    ECR_REPO: 056665234171.dkr.ecr.us-east-1.amazonaws.com/order
    ECR_REGION: us-east-1
    CONTAINER_NAME: lks-order-container

phases:
  install:
    runtime-versions:
      nodejs: 16
      docker: 20
  pre_build:
    commands:
      - echo "Install Dependencies and login into ECR"
  build:
    commands:
      - echo "Run unit testing and build docker image"
  post_build:
    commands:
      - echo "Push docker image to ECR.."
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $ECR_REPO:latest > imagedefinitions.json
      - echo "build complete.."

reports:
    test-report:
      files:
        - 'report/test-report.xml'
      file-format: JUNITXML
artifacts:
  files:
    - imagedefinitions.json
